DROP DATABASE IF EXISTS employee_db;
CREATE DATABASE employee_db;

USE employee_db;

CREATE TABLE departments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    deptName VARCHAR(30) NOT NULL
);

CREATE TABLE roles (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30) UNIQUE NOT NULL,
    salary INT UNSIGNED NOT NULL,
    departmentId INT UNSIGNED,
    FOREIGN KEY (departmentId)
    REFERENCES departments(id)
    ON DELETE CASCADE
);

CREATE TABLE employees (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(30) NOT NULL,
    lastName VARCHAR(30) NOT NULL,
    roleId INT UNSIGNED,
    FOREIGN KEY (roleId)
    REFERENCES roles(id)
    ON DELETE CASCADE,
    managerId INT UNSIGNED,
    FOREIGN KEY (managerId)
    REFERENCES employees(id)
    ON DELETE NO ACTION
);